# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class ScrapyAnalysisItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()

 #   _id = scrapy.Field()
  #  jobName = scrapy.Field()
  #  appearDate = scrapy.Field()
   # custName = scrapy.Field()
   # industry = scrapy.Field()
   # jobDescription = scrapy.Field()
   # jobCategory = scrapy.Field()
   # salary = scrapy.Field()
   # salaryMin = scrapy.Field()
   # salaryMax = scrapy.Field()
   # workExp = scrapy.Field()
   # edu = scrapy.Field()
   # language = scrapy.Field()
   # specialty = scrapy.Field()
   # skill = scrapy.Field()
   # otherRequirements = scrapy.Field()
   # welfareTag = scrapy.Field()
   # welfare = scrapy.Field()
   # address = scrapy.Field()
   # companyUrl = scrapy.Field()
   # jobUrl = scrapy.Field()
   # analysisUrl = scrapy.Field()
   # environmentPic = scrapy.Field()
   # role = scrapy.Field()
   # disRole = scrapy.Field()
   # major = scrapy.Field()
   # certificate = scrapy.Field()
   # driverLicense = scrapy.Field()
   # longitude = scrapy.Field()
   # latitude = scrapy.Field()
   # manageResp = scrapy.Field()
   # businessTrip = scrapy.Field()
   # workPeriod = scrapy.Field()
   # vacationPolicy = scrapy.Field()
   # startWorkingDay = scrapy.Field()
   # needEmp = scrapy.Field()
   # switch = scrapy.Field()
   # postalCode = scrapy.Field()
   # closeDate = scrapy.Field()

    total_applied = scrapy.Field()
    sex_male = scrapy.Field()
    sex_female = scrapy.Field()
    edu_postgrad = scrapy.Field()
    edu_grad = scrapy.Field()
    edu_likeGrad = scrapy.Field()
    edu_high = scrapy.Field()
    edu_junior = scrapy.Field()
    edu_na = scrapy.Field()
    age_na = scrapy.Field()
    age_20 = scrapy.Field()
    age_21_25 = scrapy.Field()
    age_26_30 = scrapy.Field()
    age_31_35 = scrapy.Field()
    age_36_40 = scrapy.Field()
    age_41_45 = scrapy.Field()
    age_46_50 = scrapy.Field()
    age_51_55 = scrapy.Field()
    age_56_60 = scrapy.Field()
    age_61 = scrapy.Field()
    age_avg = scrapy.Field()
    exp_na = scrapy.Field()
    exp_1 = scrapy.Field()
    exp_1_3 = scrapy.Field()
    exp_3_5 = scrapy.Field()
    exp_5_10 = scrapy.Field()
    exp_10_15 = scrapy.Field()
    exp_15_20 = scrapy.Field()
    exp_20_25 = scrapy.Field()
    exp_26 = scrapy.Field()
    exp_avg = scrapy.Field()
    commLanguage = scrapy.Field()
    commMajor = scrapy.Field()
    commSkill = scrapy.Field()
    commCert = scrapy.Field()
